FROM evernode/sashimono:hp.test-ubt.20.04-njs.20

RUN mkdir -p /deploy/contract
COPY contract/* /deploy/contract
RUN mkdir -p /usr/local/bin/hotpocket/lobby
COPY lobby/* /usr/local/bin/hotpocket/lobby
COPY startup.sh /usr/local/bin/hotpocket/startup.sh

ENTRYPOINT ["/usr/local/bin/hotpocket/startup.sh"]