FROM evernode/hotpocket:0.6.4-ubt.20.04-njs.20

RUN apt-get update \
    && apt-get install --no-install-recommends -y unzip jq \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /deploy/contract
COPY contract/* /deploy/contract
COPY hp.cfg /deploy
COPY hpcore.sh /usr/local/bin/hotpocket/
RUN chmod +x /usr/local/bin/hotpocket/hpcore.sh

ENTRYPOINT ["/usr/local/bin/hotpocket/hpcore.sh"]